[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"  # pylint: disable=invalid-name

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --cov=prompt_optimizer --cov-report=term-missing"
